[build]
rustflags = ["--remap-path-prefix=$HOME=/home", "--remap-path-prefix=$PWD=/app"]

[alias]
xtask = ["run", "-p", "xtask", "--"]
about = ["bin", "cargo-about"]
binstall = ["bin", "cargo-binstall"]
cmd = ["bin", "cargo-cmd"]
deny = ["bin", "cargo-deny"]
flamegraph = ["bin", "cargo-flamegraph"]
gha = ["bin", "cargo-gha"]
insta = ["bin", "cargo-insta"]
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
watch = ["bin", "cargo-watch"]
xwin = ["bin", "cargo-xwin"]
zigbuild = ["bin", "cargo-zigbuild"]

[env]
BINSTALL_STRATEGIES = "crate-meta-data,compile"
